name: First CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run our test
        run: |
          echo "Running CI test..."
          grep -q "Hello from CI/CD lab, Now This Text Not exist" app.txt